### ISSUE TITLE
Text content dropdown when clicking on events

### ISSUE THREAD

**Issue by colossatr0n** [kochrt/cascade.page#14]
It would be nice to be able to add more text content to an event without having to make an extremely long description. Might look something like the current photos dropdown, except that it just displays more text. There would also have to be some way to add multiline text in the timeline creator text editor.

**Comment by kochrt** [comment]
Implemented as of ed3105b99c365779eae234f04082d0f534e227a4. Still need to add instructions about how it works (#17), but basically anything written below an event up to the next event is included as supplemental text. This is indicated by an ellipsis (...), and when you click on the event it expands the supplemental text.
